In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.5'

In [5]:
# 리스트를 사용한 시리즈 생성 (인덱스 직접 지정)
population = pd.Series([940, 330, 290], index=['서울', '부산', '인천'])
print(population)

# index 확인하기
print(population.index)

# 배열 확인하기
print(population.values)

서울    940
부산    330
인천    290
dtype: int64
Index(['서울', '부산', '인천'], dtype='str')
[940 330 290]

In [6]:
# k:v 구조를 갖는 딕셔너리를 만들고, 변수 dict_data에 저장
dict_data = {'a': 1, 'b': 2, 'c': 3}
print(dict_data)            # {'a': 1, 'b': 2, 'c': 3}

# 판다스 Series() 함수로 딕셔너리(dict_data)를 시리즈로 변환. 변수 sr에 저장
sr = pd.Series(dict_data)

# 변수 sr의 자료형 출력
print(type(sr))            # <class 'pandas.core.series.Series'>

# 주피터 환경에서 변수 출력
print(sr)

'''
a    1
b    2
c    3
dtype: int64
'''
# 인덱스 배열은 변수 idx에 저장
idx = sr.index
print(idx)

# 데이터 값 배열은 변수 val에 저장
val = sr.values
print(val)

{'a': 1, 'b': 2, 'c': 3}
<class 'pandas.Series'>
a    1
b    2
c    3
dtype: int64
Index(['a', 'b', 'c'], dtype='str')
[1 2 3]

In [7]:
# 리스트를 시리즈로 변환하여 변수 sr에 저장
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr)

'''
0    2019-01-02
1          3.14
2           ABC
3           100
4          True
'''

# 인덱스 배열은 변수 idx에 저장
idx = sr.index
print(idx)                         # RangeIndex(start=0, stop=5, step=1)

# 데이터 값 배열은 변수 val에 저장
val = sr.values
print(val)                         # ['2019-01-02' 3.14 'ABC' 100 True]

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object
RangeIndex(start=0, stop=5, step=1)
['2019-01-02' 3.14 'ABC' 100 True]

In [8]:
# 투플을 시리즈로 변환(index 옵션에 인덱스 이름을 지정)
tup_data = ('영인', '2010-05-01', '여', True)
sr = pd.Series(tup_data, index=['이름', '생년월일', '성별', '학생여부'])
print(sr)

'''
이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object
'''

# 인덱스 배열은 변수 idx에 저장
idx = sr.index
print(idx)           # Index(['이름', '생년월일', '성별', '학생여부'], dtype='str')

# 데이터 값 배열은 변수 val에 저장
val = sr.values
print(val)            # ['영인' '2010-05-01' '여' True]


sr = pd.Series(tup_data)
# 인덱스 배열은 변수 idx에 저장
idx = sr.index
print(idx)              # RangeIndex(start=0, stop=4, step=1

# 데이터 값 배열은 변수 val에 저장
val = sr.values
print(val)              # ['영인' '2010-05-01' '여' True]

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object
Index(['이름', '생년월일', '성별', '학생여부'], dtype='str')
['영인' '2010-05-01' '여' True]
RangeIndex(start=0, stop=4, step=1)
['영인' '2010-05-01' '여' True]

In [9]:
# 열이름을 key로 하고, 리스트를 value로 갖는 딕셔너리 정의(2차원 배열)
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

# 판다스 DataFrame() 함수로 딕셔너리를 데이터프레임으로 변환. 변수 df에 저장.
df = pd.DataFrame(dict_data)

# df의 자료형 출력
print(type(df))


# 변수 df에 저장되어 있는 데이터프레임 객체를 출력
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [10]:
# 딕셔너리를 사용한 데이터프레임 생성
data = {
    '나이':[19,30,40],
    '직업': ['학생', '회사원', '연구원']
}
df = pd.DataFrame(data, index=['철수', '영희', '민수'])
print(df)


'''
    나이   직업
철수  19   학생
영희  30  회사원
민수  40  연구원
'''

#행 인덱스 확인하기
print(df.index)      

#열 이름 확인하기
print(df.columns)

    나이   직업
철수  19   학생
영희  30  회사원
민수  40  연구원
Index(['철수', '영희', '민수'], dtype='str')
Index(['나이', '직업'], dtype='str')

In [11]:
# 행 인덱스/열 이름 지정하여, 데이터프레임 만들기
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])

# 데이터프레임 출력하기
print(df)    

#행 인덱스 확인하기
print(df.index)      

#열 이름 확인하기
print(df.columns)  


# 행 인덱스, 열 이름 변경하기
df.index=['학생1', '학생2']
df.columns=['연령', '남녀', '소속']

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중
Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')
     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [12]:
# 행 인덱스/열 이름 지정하여, 데이터프레임 만들기
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])

# 행 인덱스, 열 이름 확인하기
print(df)

# 열 이름 중, '나이'를 '연령'으로, '성별'을 '남녀'로, '학교'를 '소속'으로 바꾸기
df = df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'})

# df 출력(변경 후)
print(df)

# df의 행 인덱스 중에서, '준서'를 '학생1'로, '예은'을 '학생2'로 바꾸기
df = df.rename(index={'준서':'학생1', '예은':'학생2' })

# df 출력(변경 후)
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중
    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중
     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [13]:
%%writefile source/num.txt
1,2,3,4,5
6,7,8,9,10

Writing source/num.txt

In [14]:
%cat source/num.txt

1,2,3,4,5
6,7,8,9,10

In [17]:
# header 키워드를 지정하지 않고 호출했을 때는 무조건 파일의 첫 줄을 header로 처리한다.
data = pd.read_csv('./source/num.txt')
print(data)

print(type(data))

   1  2  3  4   5
0  6  7  8  9  10
<class 'pandas.DataFrame'>

In [19]:
# 읽어올 파일에 header가 없으면 header=None을 설정한다.
# header 파리미터의 default : 'infer' 이다.
data = pd.read_csv('./source/num.txt', header=None)
print(data)

print(type(data))
print(dir(data))

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10
<class 'pandas.DataFrame'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_arith_method_with_reindex', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_metadata', '_mgr', '_min_count_stat_function', '_module_source', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_sanitize_column', '_select_dtypes_indices', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'between_time', 'bfill', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_hdf', 'to_html', 'to_iceberg', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [20]:
print(data[0])  # data[컬럼명]
print(type(data[0])) # pandas.core.series.Series
print(dir(data[0]))

0    1
1    6
Name: 0, dtype: int64
<class 'pandas.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_attrs', '_binop', '_can_hold_na', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_ixs', '_logical_func', '_logical_method', '_map_values', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_module_source', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'between', 'between_time', 'bfill', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [21]:
print(data.iloc[0])  # data.iloc[index]
print(type(data.iloc[0]))  # pandas.core.series.Series

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.Series'>

In [22]:
data = pd.read_csv ('./source/num.txt', header=None)
print(data)

print(data.values)
print(data.index)
print(data.columns)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
RangeIndex(start=0, stop=2, step=1)
Index([0, 1, 2, 3, 4], dtype='int64')

In [23]:
%%writefile  source/read_csv_sample.csv
c0,c1,c2,c3,c4
1,2,3,4,5
6,7,8,9,10
11,12,13,14,15

Writing source/read_csv_sample.csv

In [24]:
# 경로 폴더의 모든 파일 목록 확인하기
import os
os.listdir("./source")

['num.txt', 'read_csv_sample.csv']

In [25]:
# 파일경로를 찾고, 변수 file_path에 저장 (문자열 결합)
file_path = './source/read_csv_sample.csv'

print(file_path)

./source/read_csv_sample.csv

In [26]:
# 파일경로를 찾고, 변수 file_path에 저장 (os 모듈 활용)
file_path = os.path.join('source', 'read_csv_sample.csv')

print(file_path)

source/read_csv_sample.csv

In [27]:
# read_csv() 함수로 데이터프레임 변환. 변수 df2에 저장. header=None 옵션
df2 = pd.read_csv(file_path, header=None)
print(df2)

    0   1   2   3   4
0  c0  c1  c2  c3  c4
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15

In [28]:
# read_csv() 함수로 데이터프레임 변환. 변수 df3에 저장. index_col=None 옵션
df3 = pd.read_csv(file_path, index_col=None)
print(df3)

   c0  c1  c2  c3  c4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15

In [29]:
# read_csv() 함수로 데이터프레임 변환. 변수 df4에 저장. index_col='c0' 옵션
df4 = pd.read_csv(file_path, index_col='c0')
print(df4)

    c1  c2  c3  c4
c0
1    2   3   4   5
6    7   8   9  10
11  12  13  14  15

In [30]:
import openpyxl

In [32]:
# 1. 샘플 데이터 생성 (직원 정보 및 실적 데이터)
data = {
    '직원ID': ['EMP01', 'EMP02', 'EMP03', 'EMP04', 'EMP05'],
    '이름': ['김철수', '이영희', '박민수', '정수진', '최동현'],
    '부서': ['영업부', '개발부', '영업부', '마케팅부', '개발부'],
    '입사일': ['2021-03-01', '2019-05-15', '2022-01-10', '2020-11-01', '2023-02-01'],
    '월급(만원)': [350, 480, 310, 420, 330],
    '성과점수': [88.5, 92.0, 78.0, 95.5, 84.0]
}

df = pd.DataFrame(data)

# 2. 'Sheet1' 시트 명으로 'emp.xlsx' 저장
df.to_excel('source/emp.xlsx', sheet_name='Sheet1', index=False)

print("'emp.xlsx' 파일이 성공적으로 생성되었습니다!")

'emp.xlsx' 파일이 성공적으로 생성되었습니다!

In [33]:
# read_excel() 함수로 데이터프레임 변환: header=0 (default 옵션)
# openpyxl 설치 필요
df1 = pd.read_excel('./source/emp.xlsx', engine='openpyxl')          

# 데이터프레임 출력
df1.head()

    직원ID   이름    부서         입사일  월급(만원)  성과점수
0  EMP01  김철수   영업부  2021-03-01     350  88.5
1  EMP02  이영희   개발부  2019-05-15     480  92.0
2  EMP03  박민수   영업부  2022-01-10     310  78.0
3  EMP04  정수진  마케팅부  2020-11-01     420  95.5
4  EMP05  최동현   개발부  2023-02-01     330  84.0

In [34]:
import os
import json

# 1. source 디렉토리 생성
os.makedirs('source', exist_ok=True)

# 2. 샘플 데이터 작성
data = [
    {"직원ID": "EMP01", "이름": "김철수", "부서": "영업부", "직급": "대리", "입사일": "2021-03-01", "월급(만원)": 350, "성과점수": 88.5},
    {"직원ID": "EMP02", "이름": "이영희", "부서": "개발부", "직급": "과장", "입사일": "2019-05-15", "월급(만원)": 480, "성과점수": 92.0},
    {"직원ID": "EMP03", "이름": "박민수", "부서": "영업부", "직급": "사원", "입사일": "2022-01-10", "월급(만원)": 310, "성과점수": 78.0},
    {"직원ID": "EMP04", "이름": "정수진", "부서": "마케팅부", "직급": "차장", "입사일": "2020-11-01", "월급(만원)": 520, "성과점수": 95.5},
    {"직원ID": "EMP05", "이름": "최동현", "부서": "개발부", "직급": "사원", "입사일": "2023-02-01", "월급(만원)": 330, "성과점수": 84.0},
    {"직원ID": "EMP06", "이름": "강지훈", "부서": "기획부", "직급": "대리", "입사일": "2021-08-15", "월급(만원)": 380, "성과점수": 89.0}
]

# 3. JSON 파일 저장 (한글 깨짐 방지를 위해 ensure_ascii=False 및 encoding='utf-8' 사용)
with open('source/emp.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print("source/emp.json 파일이 성공적으로 생성되었습니다!")

source/emp.json 파일이 성공적으로 생성되었습니다!

In [35]:
# read_json() 함수로 데이터프레임 변환 
df = pd.read_json('./source/emp.json')  
print(df)

    직원ID   이름    부서  직급         입사일  월급(만원)  성과점수
0  EMP01  김철수   영업부  대리  2021-03-01     350  88.5
1  EMP02  이영희   개발부  과장  2019-05-15     480  92.0
2  EMP03  박민수   영업부  사원  2022-01-10     310  78.0
3  EMP04  정수진  마케팅부  차장  2020-11-01     520  95.5
4  EMP05  최동현   개발부  사원  2023-02-01     330  84.0
5  EMP06  강지훈   기획부  대리  2021-08-15     380  89.0

In [36]:
# 1. source 디렉토리 생성
os.makedirs('source', exist_ok=True)

# 2. 샘플 데이터 작성
data = {
    "이름": {
        "0": "김철수",
        "1": "이영희"
    },
    "부서": {
        "0": "영업부",
        "1": "개발부"
    },
    "월급": {
        "0": 350,
        "1": 480
    }
}

# 3. JSON 파일 저장 (한글 깨짐 방지를 위해 ensure_ascii=False 및 encoding='utf-8' 사용)
with open('source/emp2.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print("source/emp2.json 파일이 성공적으로 생성되었습니다!")

source/emp2.json 파일이 성공적으로 생성되었습니다!

orient는 index보다 colums를 더 많이 씀.

In [123]:
# read_json() 함수로 데이터프레임 변환 
df = pd.read_json('./source/emp2.json', orient='index')  
print(df)

      0    1
이름  김철수  이영희
부서  영업부  개발부
월급  350  480

In [38]:
# read_json() 함수로 데이터프레임 변환 
df = pd.read_json('./source/emp2.json', orient='columns')  
print(df)

    이름   부서   월급
0  김철수  영업부  350
1  이영희  개발부  480

In [128]:
# header은 기본이 첫 줄을 컬럼명으로 가져오도록 설정이 되여 있기 때문에 header='infer' 생략 가능하다.
df= pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv')
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [41]:
# 위에서부터 5개 행 조회
print(df.head())

# 위에서부터 3개 행 조회
print(df.head(3))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [42]:
# 아래에서부터 5개 행 조회
print(df.tail())

# 아래에서부터 2개 행 조회
print(df.tail(2))

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2
     total_bill   tip     sex smoker   day    time  size
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [115]:
# 무작위로 1개 행 추출
# print(df.sample())

# 무작위로 3개 행 추출
print(df.sample(3))

# 전체 데이터의 20%를 무작위로 추출 (frac 파라미터 사용)
# print(df.sample(frac=0.2))

# 실행할 때마다 동일한 난수 결과를 얻고 싶을 때 (random_state)
# print(df.sample(3, random_state=42))

     total_bill  tip     sex smoker   day    time  size
49        18.04  3.0    Male     No   Sun  Dinner     2
178        9.60  4.0  Female    Yes   Sun  Dinner     2
136       10.33  2.0  Female     No  Thur   Lunch     2

In [116]:
# 1. 크기와 이름 확인 (속성)
print(df.shape)    # 몇 행 몇 열?
print(df.columns)  # 무슨 컬럼들이 있지?
print(df.index)    # 인덱스는 어떻게 되어있지?

# 2. 요약 및 통계 확인 (메서드)
df.info()          # 결측치나 데이터 타입은 괜찮나?
df.describe()      # 숫자 데이터들의 평균/최댓값/최솟값은 얼마지?

(244, 7)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')
RangeIndex(start=0, stop=244, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

df['column']         # 컬럼(열) 하나 단순히 가져올 때    
df.loc[행라벨, 열라벨]  # 라벨(이름) 기준으로 행/열 선택 (행만 쓰면 행 전체)    
df.iloc[행위치, 열위치] # 위치(정수) 기준으로 행/열 선택 (행만 쓰면 행 전체)

In [ ]:
# print(df)
# 1. 단일 행 선택 (인덱스 이름이 0인 행)
# df.loc[0]

# 2. 여러 행 선택 (0번, 2번 행)
# df.loc[[0, 2]]

# 3. 행 슬라이싱 (주의: loc 슬라이싱은 '끝 범위'를 포함함! 0부터 2까지)
# df.loc[0:2]

# 4. 행과 열을 동시에 선택 (0~2번 행의 'tip', 'time' 열)
# df.loc[0:2, ['tip', 'time']]

# 5. 조건식(필터링) 활용 (tip이 3.0 이상인 행의 'tip', 'day' 선택)
df.loc[df['tip'] >= 3.0, ['tip', 'day']]

      tip   day
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
5    4.71   Sun
7    3.12   Sun
..    ...   ...
232  3.39   Sat
234  3.00   Sat
238  4.67   Sat
239  5.92   Sat
243  3.00  Thur

[121 rows x 2 columns]

In [ ]:
# 1. 단일 행 선택 (첫 번째 행)
# df.iloc[0]

# 2. 여러 행 선택 (0번째, 2번째 위치 행)
# df.iloc[[0, 2]]

# 3. 행 슬라이싱 (파이썬 슬라이싱처럼 '끝 범위' 미포함! 0부터 1까지)
# df.iloc[0:2]

# 4. 행과 열을 위치 기반으로 동시에 선택 (0~1번 행, 0~1번 열)
df.iloc[0:2, 0:2]

   total_bill   tip
0       16.99  1.01
1       10.34  1.66

In [145]:
# 1. 총 지불 금액(total_bill)이 30.0 초과인 데이터 검색
res1 = df[df['total_bill'] > 30.0]

# 2. 요일(day)이 'Sun'(일요일)인 데이터만 검색
res2 = df[df['day'] == 'Sun']

# 검색된 결과에서 특정 열만 출력
print(res1[['total_bill', 'day']])

     total_bill   day
11        35.26   Sun
23        39.42   Sat
39        31.27   Sat
44        30.40   Sun
47        32.40   Sun
52        34.81   Sun
56        38.01   Sat
59        48.27   Sat
83        32.68  Thur
85        34.83  Thur
95        40.17   Fri
102       44.30   Sat
112       38.07   Sun
141       34.30  Thur
142       41.19  Thur
156       48.17   Sun
167       31.71   Sun
170       50.81   Sat
173       31.85   Sun
175       32.90   Sun
179       34.63   Sun
180       34.65   Sun
182       45.35   Sun
184       40.55   Sun
187       30.46   Sun
197       43.11  Thur
207       38.73   Sat
210       30.06   Sat
212       48.33   Sat
219       30.14   Sat
237       32.83   Sat
238       35.83   Sat

In [ ]:
# AND(&): 총 지불 금액(total_bill)이 30.0 이상이고 요일(day)이 'Sun'인 데이터
# cond_and = (df['total_bill'] >= 30.0) & (df['day'] == 'Sun')
# res_and = df[cond_and]
# print(res_and)

# OR(|): 총 지불 금액(total_bill)이 40.0 이상이거나 10.0 이하인 데이터
# cond_or = (df['total_bill'] >= 40.0) | (df['total_bill'] <= 10.0)
# res_or = df[cond_or]
# print(res_or)

# NOT(~): 요일(day)이 'Thur'가 아닌 데이터
res_not = df[~(df['day'] == 'Thur')]
print(res_not)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[230 rows x 7 columns]

In [159]:
# 요일(day)이 'Sun' 또는 'Sat' (주말)인 데이터 검색
target_days = ['Sun', 'Sat']
df[df['day'].isin(target_days)]

# unique는 series에서만 사용 가능 
# day라는 컬럼의 결과값만 가지고 오기 -> 이 시리즈에서 unique만 가져오기
df[df['day'].isin(target_days)]['day'].unique()

<StringArray>
['Sun', 'Sat']
Length: 2, dtype: str

In [158]:

# 반대로 지정 목록에 없는 데이터만 뽑을 때 (~ 붙이기) -> 평일(Thur, Fri) 데이터
df[~df['day'].isin(target_days)]

     total_bill   tip     sex smoker   day    time  size
77        27.20  4.00    Male     No  Thur   Lunch     4
78        22.76  3.00    Male     No  Thur   Lunch     2
79        17.29  2.71    Male     No  Thur   Lunch     2
80        19.44  3.00    Male    Yes  Thur   Lunch     2
81        16.66  3.40    Male     No  Thur   Lunch     2
..          ...   ...     ...    ...   ...     ...   ...
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[81 rows x 7 columns]

In [160]:
# tip이 2.0 이상 3.0 이하인 데이터 검색
# df[(df['tip'] >= 2.0) & (df['tip'] <= 3.0)] 와 동일
res_between = df[df['tip'].between(2.0, 3.0)]

print(res_between[['tip', 'total_bill', 'day']].head())

     tip  total_bill  day
6   2.00        8.77  Sun
13  3.00       18.43  Sun
21  2.75       20.29  Sat
22  2.23       15.77  Sat
25  2.34       17.81  Sat

In [167]:
# 1. 기본 조건 및 논리 연산
res_query1 = df.query('total_bill > 30.0 and day == "Sun"')

# 2. 파이썬 변수를 조건식에 넣을 때 (@ 기호 사용)
min_tip = 5.0
res_query2 = df.query('tip >= @min_tip')

# 3. in 키워드 조합
res_query3 = df.query('day in ["Sun", "Sat"]')

print(res_query1[['total_bill', 'tip', 'day']].head())

     total_bill  tip  day
11        35.26  5.0  Sun
44        30.40  5.6  Sun
47        32.40  6.0  Sun
52        34.81  5.2  Sun
112       38.07  4.0  Sun

In [178]:
# 1. 총 지불 금액(total_bill) 오름차순 정렬
df.sort_values(by="total_bill")

# 2. 총 지불 금액(total_bill) 내림차순 정렬
df.sort_values(
    by="total_bill",
    ascending=False
)

# 3. 팁(tip) 기준 정렬
df.sort_values(by="tip")

# 4. 인원수(size) 내림차순 정렬
df.sort_values(
    by="size",
    ascending=False
)

# 5. 여러 컬럼 기준 정렬
# 요일(day)은 오름차순, 총 지불 금액(total_bill)은 내림차순으로 정렬한다.
df.sort_values(
    by=["day", "total_bill"],
    ascending=[True, False]
)

# 6. 원본 데이터 변경 (inplace=True)
df2 = df.copy()
print(df2.head())

df2.sort_values(
    by="tip",
    inplace=True
)
print(df2.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
     total_bill   tip     sex smoker  day    time  size
67         3.07  1.00  Female    Yes  Sat  Dinner     1
236       12.60  1.00    Male    Yes  Sat  Dinner     2
92         5.75  1.00  Female    Yes  Fri  Dinner     2
111        7.25  1.00  Female     No  Sat  Dinner     1
0         16.99  1.01  Female     No  Sun  Dinner     2

In [182]:
# 1. 인덱스를 섞어보기 (무작위 10개 추출)
sample = df.sample(10, random_state=42)
print(sample.head())

# 2. 인덱스 오름차순 정렬
print(sample.sort_index())

# 3. 인덱스 내림차순 정렬
print(sample.sort_index(
    ascending=False
))

# 4. 열(Column) 이름 정렬
# 열의 순서를 알파벳 순(sex, day, size, time, tip, total_bill 등)으로 정렬한다.
df.sort_index(axis=1)

     total_bill   tip     sex smoker   day    time  size
24        19.82  3.18    Male     No   Sat  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
153       24.55  2.00    Male     No   Sun  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
     total_bill   tip     sex smoker   day    time  size
6          8.77  2.00    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
24        19.82  3.18    Male     No   Sat  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
124       12.48  2.52  Female     No  Thur   Lunch     2
153       24.55  2.00    Male     No   Sun  Dinner     4
176       17.89  2.00    Male    Yes   Sun  Dinner     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
198       13.00  2.00  Female    Yes  Thur   Lunch     2
211       25.89  5.16    Male    Yes   Sat  Dinner     4
     total_bill   tip     sex smoker   day    time  size
211       25.89  5.16    Male    Yes   Sat  Dinner     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
176       17.89  2.00    Male    Yes   Sun  Dinner     2
153       24.55  2.00    Male     No   Sun  Dinner     4
124       12.48  2.52  Female     No  Thur   Lunch     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
24        19.82  3.18    Male     No   Sat  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2

      day     sex  size smoker    time   tip  total_bill
0     Sun  Female     2     No  Dinner  1.01       16.99
1     Sun    Male     3     No  Dinner  1.66       10.34
2     Sun    Male     3     No  Dinner  3.50       21.01
3     Sun    Male     2     No  Dinner  3.31       23.68
4     Sun  Female     4     No  Dinner  3.61       24.59
..    ...     ...   ...    ...     ...   ...         ...
239   Sat    Male     3     No  Dinner  5.92       29.03
240   Sat  Female     2    Yes  Dinner  2.00       27.18
241   Sat    Male     2    Yes  Dinner  2.00       22.67
242   Sat    Male     2     No  Dinner  1.75       17.82
243  Thur  Female     2     No  Dinner  3.00       18.78

[244 rows x 7 columns]